[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app"

